### ISSUE TITLE
Failing to upload on ImGUR

### ISSUE THREAD

**Issue by flaviopuhl** [tobozo/ImgurUploader#1] opened 2021-07-30 19:52 UTC
Hi Tobozo,

I am  trying example "Submit-From-bytes-Array", (with proper client ID and SSID+password) on an AI Thinker ESP32 Cam and this error occur when trying to upload the image:

Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400d305c  PS      : 0x00060030  A0      : 0x800d3492  A1      : 0x3ffb1d10  
A2      : 0x3ffc17a8  A3      : 0x00000064  A4      : 0x00000000  A5      : 0x0000ff00  
A6      : 0x00000064  A7      : 0x00000200  A8      : 0x800d509c  A9      : 0x00000000  
A10     : 0x00000200  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x00000000  
A14     : 0x00000000  A15     : 0x00000000  SAR     : 0x00000008  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400d3058  LEND    : 0x400d306b  LCOUNT  : 0x000001ff  

ELF file SHA256: 0000000000000000

Backtrace: 0x400d305c:0x3ffb1d10 0x400d348f:0x3ffb1f40 0x400d34d1:0x3ffb1f60 0x400d0921:0x3ffb1f80 0x400d5752:0x3ffb1fb0 0x4008d5ca:0x3ffb1fd0

An then the ESP32 CAM reboots.

Any clue?

**Comment by tobozo** [comment] 2021-08-09 18:41
hey @flaviopuhl thanks for your feedback

I've ordered an esp32-cam to test that, can you share the sketch you're using to extract the image data from the camera so I can reproduce the issue?

Meanwhile you can eventually use the esp32 [exception decoder](https://github.com/me-no-dev/EspExceptionDecoder) to see what's behing this stack trace.

Wild guesses: 

- imgur TLS certificate changed
- imgur API changed
- the esp32 cam doesn't have enough heap to hold both the image and handle TLS
- the image format isn't supported by imgur

**Comment by tobozo** [comment] 2021-08-10 16:32
@flaviopuhl I received the ESP32-Cam today and could test the example script.

Thanks to you I found the cause of this bug and fixed it on the master branch.

If you can't wait for release propagation and want to fix manually, just edit `ImgurUploader.cpp` at line 78, and replace this:
```C++
  _byteArray = (uint8_t*)_byteArray;
```
by this:
```C++
  _byteArray = (uint8_t*)byteArray;
```

**Comment by tobozo** [comment] 2021-08-10 16:37
closing this as "solved in latest release", feel free to reopen if this bug still shows up

thanks again for spotting that !

**Closed as completed by tobozo** 2021-08-10 16:37 UTC
